astrometry:
  rerun: false
  search_radius: 1
cals:
  ignore_flats: true
cleanup:
  cc_type: 1d
  clean_oba_dir: false
coadd:
  combine_type: CLIPPED
  det_combine_type: WEIGHTED
masking:
  cosmic_rays: false
  satellites: false
modules:
- preprocessing
- cals
- masking
- background
- astrometry
- starmask
- coadd
- detection
- output
- cleanup
output:
  center_stamp_size: 512
  make_2d: true
  make_center_stamp: true
run_options:
  bands:
  - u
  - b
  - g
  det_bands:
  - b
  - g
  fresh: false
  overwrite: true
  vb: true
